/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpNote.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import ups.m2dl.tpNote.ui.internal.TpNoteActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MaisonDeDisqueExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TpNoteActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TpNoteActivator activator = TpNoteActivator.getInstance();
		return activator != null ? activator.getInjector(TpNoteActivator.UPS_M2DL_TPNOTE_MAISONDEDISQUE) : null;
	}

}
