/**
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpNote.formatting2;

import albums.Album;
import albums.Chanson;
import albums.MaisonDeDisques;
import albums.Personne;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import ups.m2dl.tpNote.services.MaisonDeDisqueGrammarAccess;

@SuppressWarnings("all")
public class MaisonDeDisqueFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MaisonDeDisqueGrammarAccess _maisonDeDisqueGrammarAccess;
  
  protected void _format(final MaisonDeDisques maisonDeDisques, @Extension final IFormattableDocument document) {
    EList<Album> _albums = maisonDeDisques.getAlbums();
    for (final Album album : _albums) {
      document.<Album>format(album);
    }
    EList<Chanson> _chansons = maisonDeDisques.getChansons();
    for (final Chanson chanson : _chansons) {
      document.<Chanson>format(chanson);
    }
    EList<Personne> _personnes = maisonDeDisques.getPersonnes();
    for (final Personne personne : _personnes) {
      document.<Personne>format(personne);
    }
  }
  
  public void format(final Object maisonDeDisques, final IFormattableDocument document) {
    if (maisonDeDisques instanceof XtextResource) {
      _format((XtextResource)maisonDeDisques, document);
      return;
    } else if (maisonDeDisques instanceof MaisonDeDisques) {
      _format((MaisonDeDisques)maisonDeDisques, document);
      return;
    } else if (maisonDeDisques instanceof EObject) {
      _format((EObject)maisonDeDisques, document);
      return;
    } else if (maisonDeDisques == null) {
      _format((Void)null, document);
      return;
    } else if (maisonDeDisques != null) {
      _format(maisonDeDisques, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(maisonDeDisques, document).toString());
    }
  }
}
