/**
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import maisonDeDisque.Album;
import maisonDeDisque.Chanson;
import maisonDeDisque.MaisonDeDisque;
import maisonDeDisque.Personne;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import ups.m2dl.tpnote.services.MaisonDeDisqueGrammarAccess;

@SuppressWarnings("all")
public class MaisonDeDisqueFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MaisonDeDisqueGrammarAccess _maisonDeDisqueGrammarAccess;
  
  protected void _format(final MaisonDeDisque maisonDeDisque, @Extension final IFormattableDocument document) {
    EList<Chanson> _chansons = maisonDeDisque.getChansons();
    for (final Chanson chanson : _chansons) {
      document.<Chanson>format(chanson);
    }
    EList<Album> _albums = maisonDeDisque.getAlbums();
    for (final Album album : _albums) {
      document.<Album>format(album);
    }
    EList<Personne> _personnes = maisonDeDisque.getPersonnes();
    for (final Personne personne : _personnes) {
      document.<Personne>format(personne);
    }
  }
  
  public void format(final Object maisonDeDisque, final IFormattableDocument document) {
    if (maisonDeDisque instanceof XtextResource) {
      _format((XtextResource)maisonDeDisque, document);
      return;
    } else if (maisonDeDisque instanceof MaisonDeDisque) {
      _format((MaisonDeDisque)maisonDeDisque, document);
      return;
    } else if (maisonDeDisque instanceof EObject) {
      _format((EObject)maisonDeDisque, document);
      return;
    } else if (maisonDeDisque == null) {
      _format((Void)null, document);
      return;
    } else if (maisonDeDisque != null) {
      _format(maisonDeDisque, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(maisonDeDisque, document).toString());
    }
  }
}
