/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMaisonDeDisqueScopeProvider extends DelegatingScopeProvider {
}
