/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MaisonDeDisqueUiModule extends AbstractMaisonDeDisqueUiModule {

	public MaisonDeDisqueUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
