/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.ide;


/**
 * Use this class to register ide components.
 */
public class MaisonDeDisqueIdeModule extends AbstractMaisonDeDisqueIdeModule {
}
