/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpNote.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ups.m2dl.tpNote.MaisonDeDisqueRuntimeModule;
import ups.m2dl.tpNote.MaisonDeDisqueStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MaisonDeDisqueIdeSetup extends MaisonDeDisqueStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MaisonDeDisqueRuntimeModule(), new MaisonDeDisqueIdeModule()));
	}
	
}
