/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MaisonDeDisqueAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ups/m2dl/tpnote/parser/antlr/internal/InternalMaisonDeDisque.tokens");
	}
}
