/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpNote.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ups.m2dl.tpNote.parser.antlr.internal.InternalMaisonDeDisqueParser;
import ups.m2dl.tpNote.services.MaisonDeDisqueGrammarAccess;

public class MaisonDeDisqueParser extends AbstractAntlrParser {

	@Inject
	private MaisonDeDisqueGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMaisonDeDisqueParser createParser(XtextTokenStream stream) {
		return new InternalMaisonDeDisqueParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MaisonDeDisques";
	}

	public MaisonDeDisqueGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MaisonDeDisqueGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
