/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MaisonDeDisqueStandaloneSetup extends MaisonDeDisqueStandaloneSetupGenerated {

	public static void doSetup() {
		new MaisonDeDisqueStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
