/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpnote.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ups.m2dl.tpnote.ui.internal.TpnoteActivator;

public class MaisonDeDisqueUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TpnoteActivator.getInstance().getInjector("ups.m2dl.tpnote.MaisonDeDisque");
	}

}
