/*
 * generated by Xtext 2.25.0
 */
package ups.m2dl.tpNote.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ups.m2dl.tpNote.ui.internal.TpNoteActivator;

public class MaisonDeDisqueUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TpNoteActivator.getInstance().getInjector("ups.m2dl.tpNote.MaisonDeDisque");
	}

}
