<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albums" nsURI="http://ups/m2/TPNote/albums" nsPrefix="abm">
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anneeSortie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AlbumsType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chansons" lowerBound="1"
        upperBound="-1" eType="#//Chanson"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbumsType">
    <eLiterals name="SINGLE"/>
    <eLiterals name="COMPILATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chanson">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chanteurs" lowerBound="1"
        upperBound="-1" eType="#//Personne" eOpposite="#//Personne/chansonsChanteur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auteur" lowerBound="1"
        upperBound="-1" eType="#//Personne" eOpposite="#//Personne/chansonsAuteur"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Personne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chansonsChanteur" upperBound="-1"
        eType="#//Chanson" eOpposite="#//Chanson/chanteurs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chansonsAuteur" upperBound="-1"
        eType="#//Chanson" eOpposite="#//Chanson/auteur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaisonDeDisques">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albums" lowerBound="1"
        upperBound="-1" eType="#//Album" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chansons" lowerBound="1"
        upperBound="-1" eType="#//Chanson" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personnes" lowerBound="1"
        upperBound="-1" eType="#//Personne" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
